export const inkomstenTransactions = [
  {
    id: "1",
    week: 1,
    client: "Bouwbedrijf Sebze",
    from: "Den Haag",
    to: "Rotterdam",
    distanceKm: "142",
    hoursWorked: 40,
    description: "Fotoshoot",
    amount: 1440,
    date: "23-04-2025",
  },
  {
    id: "2",
    week: 2,
    client: "Bouwbedrijf Sebze",
    from: "Den Haag",
    to: "Rotterdam",
    distanceKm: "142",
    hoursWorked: 40,
    description: "Fotoshoot",
    amount: 1440,
    date: "23-04-2025",
  },
  {
    id: "3",
    week: 3,
    client: "Bouwbedrijf Sebze",
    from: "Den Haag",
    to: "Rotterdam",
    distanceKm: "142",
    hoursWorked: 40,
    description: "Fotoshoot",
    amount: 1440,
    date: "23-04-2025",
  },
  {
    id: "4",
    week: 4,
    client: "Bouwbedrijf Sebze",
    from: "Den Haag",
    to: "Rotterdam",
    distanceKm: "142",
    hoursWorked: 40,
    description: "Fotoshoot",
    amount: 1440,
    date: "23-04-2025",
  },
  {
    id: "5",
    week: 5,
    client: "Bouwbedrijf Sebze",
    from: "Den Haag",
    to: "Rotterdam",
    distanceKm: "142",
    hoursWorked: 40,
    description: "Fotoshoot",
    amount: 1440,
    date: "23-04-2025",
  },
]
//!!!!!!!!!!!!!!!!!!!!!!!

export const uitgevenTransactions = [
  {
    id: "1",
    description: "Broek",
    amount: 149,
    date: "23-04-2025",
  },
  {
    id: "2",
    description: "Hammer",
    amount: 700,
    date: "23-04-2025",
  },
  {
    id: "3",
    description: "Diesel",
    amount: 321,
    date: "23-04-2025",
  },
  {
    id: "4",
    description: "Diesel",
    amount: 4565,
    date: "23-04-2025",
  },
  {
    id: "5",
    description: "Auto",
    amount: 999,
    date: "23-04-2025",
  },
  {
    id: "6",
    description: "Auto",
    amount: 213,
    date: "23-04-2025",
  },
  {
    id: "7",
    description: "Water",
    amount: 24,
    date: "23-04-2025",
  },
  {
    id: "8",
    description: "Diesel",
    amount: 149,
    date: "23-04-2025",
  },
  {
    id: "9",
    description: "Auto",
    amount: 666,
    date: "23-04-2025",
  },
]
